trigger:
  branches:
    include:
    - master
    - develop
    - release/*
    - refs/tags/*
  paths:
    exclude:
    - CHANGELOG.md
    - /*.md
    - .gitignore
    - appveyor.yml
  # waiting for feature to become available
  # tags:
  #   include:
  #   - v/*

# add nf-tools repo to resources (for Azure Pipelines templates)
resources:
  repositories:
    - repository: templates
      type: github
      name: nanoframework/nf-tools
      endpoint: nanoframework

jobs:

##############################
- job: Build
  condition: eq(variables['UPDATE_DEPENDENTS'], 'false')
  pool:
    vmImage: 'VS2017-Win2016'

  variables:
    solution: '**/source/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    nugetPackageName: 'nanoFramework.System.Text'
    repoName: 'lib-nanoFramework.System.Text'

  steps:

  # step from template @ nf-tools repo
  # all build, update and publish steps
  - template: azure-pipelines-templates/class-lib-build.yml@templates  
    parameters:
      sonarCloudProject: 'nanoframework_lib-nanoFramework.System.Text'

##################################
# report build failure to Discord
- job: Report_Build_Failure
  
  dependsOn:
  - Build
  condition: failed('Build_mscorlib')

  pool:
    vmImage: 'VS2017-Win2016'

  steps:
  
  - checkout: self

  # step from template @ nf-tools repo
  # report error
  - template: azure-pipelines-templates/discord-webhook-task.yml@templates  
    parameters:
      status: 'failure'
      webhookUrl: '$(DiscordWebhook)'
      message: ''
